image: docker:latest

services:
  - docker:dind

.job_template: &job_definition
  only:
    - schedules
  script:
    - ./images/scripts/build.sh --push "${BUILD_GROUP}"

.job-template: &php_job_definition
  only:
    - schedules
  script:
    - for BUILD_PHP_VERSION in ${PHP_VERSION_LIST} ; do
        export PHP_VERSION=${BUILD_PHP_VERSION}
        for BUILD_GROUP in ${BUILD_GROUP_LIST} ; do
          ./images/scripts/build.sh --push "${BUILD_GROUP}"
        done
      done

stages:
  - build_php
  - build_elasticsearch
  - build_mailhog
  - build_mariadb
  - build_mysql
  - build_nginx
  - build_rabbitmq
  - build_redis
  - build_varnish
  - build_magepack

before_script:
  - docker info
  - apk update && apk add bash

##############################

build_php:
  <<: *php_job_definition
  stage: build_php

#build_php_71:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm
#    PHP_VERSION: "7.1"

#build_php_72:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm
#    PHP_VERSION: "7.2"

#build_php_73:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm
#    PHP_VERSION: "7.3"

#build_php_74:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm
#    PHP_VERSION: "7.4"

#build_php_80:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm
#    PHP_VERSION: "8.0"

##############################

#build_magento1_php_56:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm/magento1
#    PHP_VERSION: "5.6"

#build_magento1_php_71:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm/magento1
#    PHP_VERSION: "7.1"

#build_magento1_php_72:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm/magento1
#    PHP_VERSION: "7.2"

#build_magento1_php_73:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm/magento1
#    PHP_VERSION: "7.3"

##############################

#build_magento2_php_71:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm/magento2
#    PHP_VERSION: "7.1"

#build_magento2_php_72:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm/magento2
#    PHP_VERSION: "7.2"

#build_magento2_php_73:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm/magento2
#    PHP_VERSION: "7.3"

#build_magento2_php_74:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm/magento2
#    PHP_VERSION: "7.4"

#build_magento2_php_80:
#  <<: *job_definition
#  stage: build_php
#  variables:
#    BUILD_GROUP: php-fpm/magento2
#   PHP_VERSION: "8.0"

##############################

build_elasticsearch:
  <<: *job_definition
  stage: build_elasticsearch
  variables:
    BUILD_GROUP: elasticsearch

##############################

build_mailhog:
  <<: *job_definition
  stage: build_mailhog
  variables:
    BUILD_GROUP: mailhog

##############################

build_mariadb:
  <<: *job_definition
  stage: build_mariadb
  variables:
    BUILD_GROUP: mariadb

##############################

build_mysql:
  <<: *job_definition
  stage: build_mysql
  variables:
    BUILD_GROUP: mysql

##############################

build_nginx:
  <<: *job_definition
  stage: build_nginx
  variables:
    BUILD_GROUP: nginx

##############################

build_rabbitmq:
  <<: *job_definition
  stage: build_rabbitmq
  variables:
    BUILD_GROUP: rabbitmq

##############################

build_redis:
  <<: *job_definition
  stage: build_redis
  variables:
    BUILD_GROUP: redis

##############################

build_varnish:
  <<: *job_definition
  stage: build_varnish
  variables:
    BUILD_GROUP: varnish

##############################

build_magepack:
  <<: *job_definition
  stage: build_magepack
  variables:
    BUILD_GROUP: magepack
