services:
  tmp-db:
    hostname: "${WARDEN_ENV_NAME}-tmp-db"
    image: ${WARDEN_IMAGE_REPOSITORY}/${DB_DISTRIBUTION:-mysql}:${DB_DISTRIBUTION_VERSION:-${MYSQL_VERSION:-8.0}}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-magento}
      - MYSQL_DATABASE=magento_integration_tests
      - MYSQL_USER=${DB_USER:-magento}
      - MYSQL_PASSWORD=${DB_PASSWORD:-magento}
    command:
      - mysqld
      - --max_allowed_packet=1024M
      - --explicit_defaults_for_timestamp=on
    volumes:
      - tmp-dbdata:/var/lib/mysql

volumes:
  tmp-dbdata:
    driver_opts:
      type: tmpfs
      device: tmpfs
