services:
  php-fpm:
    depends_on:
      - db

  db:
    hostname: "${WARDEN_ENV_NAME}-mariadb"
    image: ${WARDEN_IMAGE_REPOSITORY}/${DB_DISTRIBUTION:-mariadb}:${DB_DISTRIBUTION_VERSION:-${MARIADB_VERSION:-10.4}}
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-app}
      - MARIADB_DATABASE=${DB_DATABASE:-app}
      - MARIADB_USER=${DB_USER:-app}
      - MARIADB_PASSWORD=${DB_PASSWORD:-app}
      - MYSQL_HISTFILE=/sql_history/.sql_history
    volumes:
      - dbdata:/var/lib/mysql
      - sqlhistory:/sql_history

volumes:
  dbdata:
  sqlhistory:
