services:
  php-fpm:
    depends_on:
      - db

  db:
    hostname: "${WARDEN_ENV_NAME}-mariadb"
    image: ${WARDEN_IMAGE_REPOSITORY}/${DB_DISTRIBUTION:-mysql}:${DB_DISTRIBUTION_VERSION:-${MYSQL_VERSION:-8.0}}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-app}
      - MYSQL_DATABASE=${DB_DATABASE:-app}
      - MYSQL_USER=${DB_USER:-app}
      - MYSQL_PASSWORD=${DB_PASSWORD:-app}
      - MYSQL_HISTFILE=/sql_history/.sql_history
    volumes:
      - dbdata:/var/lib/mysql
      - sqlhistory:/sql_history

volumes:
  dbdata:
  sqlhistory:
