x-volumes: &volumes
  - ${WARDEN_SSL_DIR}/rootca/certs:/etc/ssl/warden-rootca-cert:ro
  - ${WARDEN_COMPOSER_DIR}:/home/www-data/.composer:cached
  - .${WARDEN_WEB_ROOT:-}/:/var/www/html:cached
  - bashhistory:/bash_history
  - sshdirectory:/home/www-data/.ssh

x-extra_hosts: &extra_hosts
  - ${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
  - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}

services:
  nginx:
    depends_on:
      - php-fpm

  php-fpm:
    hostname: "${WARDEN_ENV_NAME}-php-fpm"
    image: ${WARDEN_IMAGE_REPOSITORY}/php-fpm${WARDEN_SVC_PHP_IMAGE_SUFFIX:-}:${PHP_VERSION:-7.4}${WARDEN_SVC_NODE_VARIANT:-}${WARDEN_SVC_PHP_VARIANT:-}
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - WARDEN_MAIL_SERVICE=${WARDEN_MAIL_SERVICE:-buggregator}
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_PATH_ENV:-/tmp/ssh-auth.sock}
      - NODE_VERSION=${NODE_VERSION:-}
      - COMPOSER_VERSION=${COMPOSER_VERSION:-1}
      - COMPOSER_MEMORY_LIMIT=-1
      - VAR_DUMPER_FORMAT=server
      - VAR_DUMPER_SERVER=${VAR_DUMPER_SERVER:-buggregator:9912}
      - MONOLOG_SERVER=${MONOLOG_SERVER:-buggregator:9913}
      - HISTFILE=/bash_history/.bash_history
      - CHOWN_DIR_LIST=${CHOWN_DIR_LIST:-}
    volumes: *volumes
    extra_hosts: *extra_hosts

  php-debug:
    hostname: "${WARDEN_ENV_NAME}-php-debug"
    image: ${WARDEN_IMAGE_REPOSITORY}/php-fpm${WARDEN_SVC_PHP_IMAGE_SUFFIX:-}:${PHP_VERSION:-7.4}${WARDEN_SVC_NODE_VARIANT:-}${WARDEN_SVC_PHP_VARIANT:-}-${XDEBUG_VERSION:-debug}
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - WARDEN_MAIL_SERVICE=${WARDEN_MAIL_SERVICE:-buggregator}
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_PATH_ENV:-/tmp/ssh-auth.sock}
      - NODE_VERSION=${NODE_VERSION:-}
      - COMPOSER_VERSION=${COMPOSER_VERSION:-1}
      - COMPOSER_MEMORY_LIMIT=-1
      - PHP_IDE_CONFIG=serverName=${WARDEN_ENV_NAME}-docker
      - VAR_DUMPER_FORMAT=server
      - VAR_DUMPER_SERVER=${VAR_DUMPER_SERVER:-buggregator:9912}
      - MONOLOG_SERVER=${MONOLOG_SERVER:-buggregator:9913}
      - HISTFILE=/bash_history/.bash_history
      - CHOWN_DIR_LIST=${CHOWN_DIR_LIST:-}
    volumes: *volumes
    extra_hosts: *extra_hosts
    depends_on:
      - php-fpm
volumes:
  bashhistory:
  sshdirectory:
